import { useMemo, useState } from 'react';
import type { WalletSession } from '../wallet/types';
import { Header } from '../components/Header';
import { clearReceipts, loadReceipts } from '../lib/receipts';

export function VerifiedPage({
  wallet,
  onDisconnect,
  onBackToMarket,
}: {
  wallet: WalletSession;
  onDisconnect: () => void;
  onBackToMarket: () => void;
}) {
  const [nonce, setNonce] = useState(0);

  const receipts = useMemo(() => {
    // cheap reload trigger
    void nonce;
    return loadReceipts();
  }, [nonce]);

  return (
    <div className="min-h-screen bg-[#0a0e1a]">
      <Header wallet={wallet} onDisconnect={onDisconnect} />

      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="flex items-center justify-between gap-4 mb-6">
          <button
            onClick={onBackToMarket}
            className="px-3 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-sm text-slate-200 cursor-pointer"
          >
            ← Back to Market
          </button>

          <div className="flex gap-2">
            <button
              onClick={() => {
                clearReceipts();
                setNonce(n => n + 1);
              }}
              className="px-3 py-2 rounded-lg bg-red-600/20 hover:bg-red-600/30 border border-red-500/30 text-sm text-red-300 cursor-pointer"
            >
              Clear receipts
            </button>
          </div>
        </div>

        <section className="rounded-2xl border border-[#1e293b] bg-[#111827] p-6">
          <h1 className="text-2xl font-bold text-white">Verified</h1>
          <p className="text-slate-400 mt-1">
            Local execution receipts generated by this demo (latest 50). Use these in the 3/9 proof bundle.
          </p>

          {receipts.length === 0 ? (
            <div className="mt-6 p-6 rounded-xl border border-[#1e293b] bg-[#0f172a] text-slate-400">
              No receipts yet. Go purchase a Bazaar-native skill (DRY_RUN) to generate one.
            </div>
          ) : (
            <div className="mt-6 space-y-3">
              {receipts.map(r => (
                <div
                  key={r.id}
                  className="rounded-xl border border-[#1e293b] bg-[#0f172a] p-4"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="text-white font-semibold">🧾 {r.skill.name}</p>
                      <p className="text-xs text-slate-500 mt-1">
                        {new Date(r.created_at).toLocaleString()} · {r.wallet_provider} · {r.chain}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-sm text-slate-200">${r.amount} {r.token}</p>
                      <p className="text-xs text-slate-500">{r.skill.source}</p>
                    </div>
                  </div>

                  <div className="mt-3 text-sm">
                    <p className="text-slate-500 text-xs">Tx Hash</p>
                    <div className="flex items-center justify-between gap-3">
                      <p className="font-mono text-cyan-300 break-all">{r.tx_hash}</p>
                      <a
                        href={r.explorer_url}
                        target="_blank"
                        rel="noreferrer"
                        className="text-xs text-cyan-300 underline whitespace-nowrap"
                      >
                        Open explorer ↗
                      </a>
                    </div>
                  </div>

                  <details className="mt-3">
                    <summary className="text-xs text-slate-400 cursor-pointer hover:underline">
                      View proof JSON
                    </summary>
                    <pre className="mt-2 text-xs bg-[#0a0e1a] p-3 rounded-lg text-slate-400 overflow-auto max-h-64">
{JSON.stringify(r.proof, null, 2)}
                    </pre>
                  </details>
                </div>
              ))}
            </div>
          )}
        </section>
      </main>
    </div>
  );
}
